name: Unit test and Instrumentation Tests

on:
  pull_request:

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

  android_tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          script: ./gradlew connectedAndroidTest

