[versions]
accompanist_version = '0.23.1'
activity_compose_version = "1.4.0"
android_core_version = "1.8.0"
android_test_ext_version = "1.1.3"
appcompat_version = "1.4.2"
barcode_scanning_version = '17.0.2'
camera_lifecycle_version = "1.0.2"
camerax_version = '1.1.0'
coil_version = '2.1.0'
compose_version = '1.1.1'
constraintlayout_compose_version = "1.0.1"
espresso_core_version = "3.4.0"
hilt_navigation_compose_version = "1.0.0"
hilt_version = '2.42'
junit_version = "4.13.2"
kotlin = '1.6.10'
lifecycle_version = '2.4.1'
material_version = '1.6.1'
nav_version = '2.4.2'
okhttp3_logging_version = '4.10.0'
retrofit_version = '2.9.0'
room_version = '2.4.2'
serialization_converter_version = '0.8.0'
serialization_version = '1.3.3'
timber_version = '5.0.1'
detekt-plugin = '1.20.0'
detekt-formatting_plugin = "1.16.0"
detekt-compose-plugin = "1.0.1"
android-plugin = "7.2.1"


[libraries]



[plugins]
android = { id = "com.android.application", version.ref = "android_plugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt_plugin" }
