name: continuous integration

on:
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build app variants
        run: ./gradlew assemble --stacktrace

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace --no-daemon

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'app/build/test-results/testDebugUnitTest/TEST-*.xml'

      - name: Check static analysis with detekt and lint
        run: ./gradlew detekt lintDebug --continue --no-daemon
        if: always()

      - name: Upload detekt report
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: app/build/reports/detekt/detekt.sarif
          category: detekt

      - name: Upload lint report
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: app/build/reports/lint-results-debug.sarif
          category: lint


  android_tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest --continue --no-daemon
